import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { mkdirSync, existsSync } from "fs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

// Ensure plugin directory exists
if (!existsSync('plugin')) {
	mkdirSync('plugin', { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'plugin/main.js',
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	// Copy files once at start of dev mode
	const { execSync } = await import('child_process');
	execSync('node copy-plugin-files.mjs', { stdio: 'inherit' });
	await context.watch();
}
